<?php
require __DIR__ . '/../includes/header.php';

if (empty($_SESSION['is_admin'])) {
    redirect('admin-login');
}

// Handle AJAX toggle updates
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['ajax_update'])) {
    ob_end_clean(); // Clear any HTML generated by header.php
    header('Content-Type: application/json');
    $id = (int)$_POST['id'];
    $field = $_POST['field'];
    $value = (int)$_POST['value'] ? 1 : 0;
    
    if (in_array($field, ['is_paid', 'is_dispatched', 'is_delivered'])) {
        $stmt = $pdo->prepare("UPDATE inquiries SET $field = :val WHERE id = :id");
        $stmt->execute(['val' => $value, 'id' => $id]);
        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['success' => false, 'message' => 'Invalid field']);
    }
    exit;
}

// Fetch all inquiries with shipping details
$stmt = $pdo->query("
    SELECT i.id, i.total_amount, i.is_paid, i.is_dispatched, i.is_delivered, s.shipping_name 
    FROM inquiries i
    LEFT JOIN shipping_details s ON i.id = s.inquiry_id
    ORDER BY i.id DESC
");
$reports = $stmt->fetchAll();
?>

<section class="section-padding bg-surface">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h1 class="h2-section mb-0">Order Tracking Report</h1>
            <a href="<?= url('admin-dashboard') ?>" class="btn-outline-primary btn-sm">Back to Dashboard</a>
        </div>
        
        <div class="card shadow-sm border-0">
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead class="bg-light">
                        <tr>
                            <th class="ps-4 py-3">S.No (Order #)</th>
                            <th class="py-3">Customer Name</th>
                            <th class="py-3">Amount to Pay</th>
                            <th class="py-3 text-center">Payment Status</th>
                            <th class="py-3 text-center">Dispatched</th>
                            <th class="pe-4 py-3 text-center">Delivered</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (count($reports) > 0): ?>
                            <?php foreach ($reports as $index => $row): ?>
                            <tr>
                                <td class="ps-4 py-3 fw-bold">#<?= htmlspecialchars($row['id']) ?></td>
                                <td class="py-3 fw-medium"><?= htmlspecialchars($row['shipping_name'] ?? 'Unknown') ?></td>
                                <td class="py-3 text-accent fw-bold">₹<?= number_format($row['total_amount'], 2) ?></td>
                                
                                <td class="py-3 text-center">
                                    <div class="form-check form-switch d-flex justify-content-center">
                                        <input class="form-check-input status-toggle" type="checkbox" role="switch" data-id="<?= $row['id'] ?>" data-field="is_paid" <?= $row['is_paid'] ? 'checked' : '' ?> style="cursor: pointer; transform: scale(1.2);">
                                    </div>
                                </td>
                                
                                <td class="py-3 text-center">
                                    <div class="form-check form-switch d-flex justify-content-center">
                                        <input class="form-check-input status-toggle" type="checkbox" role="switch" data-id="<?= $row['id'] ?>" data-field="is_dispatched" <?= $row['is_dispatched'] ? 'checked' : '' ?> style="cursor: pointer; transform: scale(1.2);">
                                    </div>
                                </td>
                                
                                <td class="pe-4 py-3 text-center">
                                    <div class="form-check form-switch d-flex justify-content-center">
                                        <input class="form-check-input status-toggle" type="checkbox" role="switch" data-id="<?= $row['id'] ?>" data-field="is_delivered" <?= $row['is_delivered'] ? 'checked' : '' ?> style="cursor: pointer; transform: scale(1.2);">
                                    </div>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="6" class="text-center py-5 text-muted">No orders found.</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<!-- Toast for notifications -->
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
    <div id="statusToast" class="toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body fw-bold">
                Status updated successfully!
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const toggles = document.querySelectorAll('.status-toggle');
    const toastEl = document.getElementById('statusToast');
    const toast = new bootstrap.Toast(toastEl);
    
    toggles.forEach(toggle => {
        toggle.addEventListener('change', function() {
            const id = this.getAttribute('data-id');
            const field = this.getAttribute('data-field');
            const value = this.checked ? 1 : 0;
            
            // Send AJAX request to self
            const formData = new FormData();
            formData.append('ajax_update', '1');
            formData.append('id', id);
            formData.append('field', field);
            formData.append('value', value);
            
            fetch(window.location.href, {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    toast.show();
                } else {
                    alert('Failed to update status');
                    this.checked = !this.checked; // Revert
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert('An error occurred');
                this.checked = !this.checked; // Revert
            });
        });
    });
});
</script>

<?php require __DIR__ . '/../includes/footer.php'; ?>
